# Generated by Django 5.2.1 on 2025-05-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_companyinfo_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
