# Generated by Django 5.2.1 on 2025-05-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_delete_companyinfo_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('video', models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Видео о компании')),
                ('history', models.TextField(blank=True, verbose_name='История по годам (можно JSON или просто текст)')),
                ('requisites', models.TextField(blank=True, help_text='Например: ИНН, ОГРН, юр. адрес и пр.', verbose_name='Реквизиты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
